version: '2'
services:
    rails:
        image: rails:5.0.0.1
        hostname: "${PROJECT_NAME}Rails"
        container_name: "${PROJECT_NAME}Rails"
        ports:
            - "${RAILS_PORT}:3000"
            - "${DOCS_PORT}:8808"
        volumes:
            - ./src:/usr/src/app
        working_dir: /usr/src/app
        links:
            - postgresql
        entrypoint: ./postinstall.sh
    postgresql:
        image: postgres:9.6
        hostname: "${PROJECT_NAME}Postgres"
        container_name: "${PROJECT_NAME}Postgres"
        volumes_from:
            - data
        environment:
            POSTGRES_PASSWORD: "${POSTGRESQL_PASSWORD}"
            POSTGRES_USER: "${POSTGRESQL_USER}"
            POSTGRES_DB: "${POSTGRESQL_DB}"
    data:
        image: postgres:9.6
        hostname: "${PROJECT_NAME}PostgresData"
        container_name: "${PROJECT_NAME}PostgresData"
        volumes:
            - /var/lib/postgresql/data
        command: "true"
    pg-admin:
        image: fenglc/pgadmin4
        hostname: "${PROJECT_NAME}PostgresPGAdmin"
        container_name: "${PROJECT_NAME}PostgresPGAdmin"
        ports:
            - "${PGADMIN_PORT}:5050"
        links:
            - postgresql:postgres
        volumes:
            - /etc/localtime:/etc/localtime
